import { z } from "zod";
import {
  stringSchema,
  emailSchema,
  phoneSchema,
  socialAccountSchemaOptional,
  onlyNumbersSchema,
  dateSchemaRequired,
  TfnSchema,
  havePartnerSchema,
  isHelpSchema,
  AbnSchema,
  contractSchemaRequired,
  groupSchema,
} from "./validation.utils";

export const updateProfileSchema = z.object({
  firstname: stringSchema,
  lastname: stringSchema,
  groupName: z.nullable(groupSchema),
  email: emailSchema,
  phone: phoneSchema,
  mediaKitLink: stringSchema,
  tiktokProfile: stringSchema,
  instagramProfile: stringSchema,
  youtubeProfile: z.nullable(socialAccountSchemaOptional),
  streetAddress: stringSchema,
  contractStartDate: contractSchemaRequired,
  contractEndDate: contractSchemaRequired,
  state: stringSchema,
  TFN: TfnSchema,
  ABN: AbnSchema,
  isHelp: isHelpSchema,
  bankAccountName: stringSchema,
  bankBSB: stringSchema,
  bankAccountNumber: onlyNumbersSchema,
  superFundName: z.string(),
  superFundBillerCode: onlyNumbersSchema,
  superFundReferenceNumber: z.string(),
  birthday: dateSchemaRequired,
  age: onlyNumbersSchema.or(z.number()),
  giftIdeas: stringSchema,
  havePartner: havePartnerSchema,
  alcohol: stringSchema,
  leftOrRightHand: stringSchema.or(z.number()),
  shoeSize: z.string(),
  dreamHolidayDestination: stringSchema,
  dreamBrandCollaboration: stringSchema,
  dreamCar: stringSchema,
  milkOfChoice: stringSchema,
  yourPhone: stringSchema,
  yourPhoneProvider: stringSchema,
  investmentService: z.string(),
  supermarket: z.string(),
  chemistOfChoice: z.string(),
  bottleshopOfChoice: z.string(),
  internetProvider: z.string(),
  charityOfChoice: z.string(),
  streaming: stringSchema,
  musicStreamingOfChoice: stringSchema,
  notes: z.string(),
});
