export enum QueryKeys {
  YoutubeLocalStatistics = "youtube-local-statistics",
  YoutubeLocalStatisticsLogs = "youtube-local-statistics-logs",
  YoutubePostsStatistics = "youtube-posts-statistics",
  InstagramLocalStatistics = "instagram-local-statistics",
  InstagramLocalStatisticsLogs = "instagram-local-statistics-logs",
  TikTokLocalStatistics = "tik-tok-local-statistics",
  TikTokLocalStatisticsLogs = "tik-tok-local-statistics-logs",
  TikTokPostsStatistics = "tik-tok-posts-statistics",
  Placements = "placements",
  PlacementsLastLogs = "placements-last-logs",
  PlacementLog = "placement-log",
  Quotes = "quotes",
  Quote = "quote",
  QuoteLog = "quote-log",
  SharableQuote = "quote",
}
